global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - ${ALERTMANAGER_HOST}:${ALERTMANAGER_PORT}

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - ${PROMETHEUS_HOST}:${PROMETHEUS_PORT}

  - job_name: "node-exporter"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - ${NODE_EXPORTER_HOST}:${NODE_EXPORTER_PORT}

  - job_name: "cadvisor"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - ${CADVISOR_HOST}:${CADVISOR_PORT}

  - job_name: "nginxlog-exporter"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - ${NGINXLOG_EXPORTER_HOST}:${NGINXLOG_EXPORTER_PORT}
