groups:
  - name: CriticalAlerts
    rules:
      - alert: ServiceDown
        expr: time() - container_last_seen > 60
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "🚨 Сервис '{{ $labels.name }}' недоступен более 1 минуты. 🚨"
          description: "Сервис '{{ $labels.name }}' недоступен."

      - alert: ServiceDownLong
        expr: time() - container_last_seen > 300
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "🚨 Сервис '{{ $labels.name }}' недоступен более 5 минут. 🚨"
          description: "Сервис '{{ $labels.name }}' недоступен."

      - alert: DiskSpaceUsageWarning
        expr: 100 - (node_filesystem_avail_bytes{fstype!="tmpfs",fstype!="devtmpfs"} * 100 / node_filesystem_size_bytes{fstype!="tmpfs",fstype!="devtmpfs"}) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Диск заполнен более чем на 90%."
          description: "Высокая загрузка диска на {{ $labels.instance }}"

      - alert: DiskSpaceUsageCritical
        expr: 100 - (node_filesystem_avail_bytes{fstype!="tmpfs",fstype!="devtmpfs"} * 100 / node_filesystem_size_bytes{fstype!="tmpfs",fstype!="devtmpfs"}) > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "🚨 Высокая загрузка диска на {{ $labels.instance }} 🚨"
          summary: "Диск заполнен на 95%. Проверьте диск!"

      - alert: DiskInodeUsageCritical
        expr: 100 - (node_filesystem_files_free{fstype!="tmpfs",fstype!="devtmpfs"} * 100 / node_filesystem_files{fstype!="tmpfs",fstype!="devtmpfs"}) > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "🚨 Высокая загрузка inode на {{ $labels.instance }} 🚨"
          summary: "Inode заполнены на 95%. Проверьте диск!"

      - alert: CPUUsageCritical
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "🚨 Высокая загрузка CPU на {{ $labels.instance }} 🚨"
          summary: "CPU > 90% более 5 минут."

      - alert: RAMUsageWarning
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "Высокая загрузка памяти на {{ $labels.instance }}"
          summary: "RAM > 85% более 5 минут."

      - alert: RAMUsageCritical
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "🚨 Высокая загрузка памяти на {{ $labels.instance }} 🚨"
          summary: "RAM > 90% более 1 минуты."

      - alert: NetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) > 0 or rate(node_network_transmit_errs_total[5m]) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          description: "Обнаружены ошибки сети (receive/transmit errors) на {{ $labels.instance }}"
          summary: "Обнаружены ошибки сети (receive/transmit errors)."

      - alert: NginxHigh5xxErrorRate
        expr: sum(increase(nginx_http_response_count_total{status=~"5.."}[1m])) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "🚨 Высокий уровень ошибок 5xx на nginx ({{ $value }} за минуту) на {{ $labels.instance }}. 🚨"
          summary: "Более 10 ошибок 5xx за последнюю минуту."
